### PR TITLE
hx env push/pull fixes for deleted and new environments

### LINKED ISSUE #225: hx env push to an environment created after project creation fails with `querystring/secretKeyId must be >= 1`
If you create an environment on an existing project and then try to `hx env push`, it will fail with:

```
hx env push -v
❗error -  failed to update cloud errortest environment: bad request: querystring/secretKeyId must be >= 1
✅ pushed: everything is up to date
   skipped: default, development, production
```

Image

(Note that the screenshot also shows another bug, #226, where deleted environments are being pulled even after they are deleted)

## Repro Steps
1. Create a new project
2. Add a new environment to that project
3. `hx env pull` for that project; note the new environment will not be pullef
4. Create a .env file for the new environment
5. `hx env push`

## Video Example

https://www.loom.com/share/799279b6d84b40848f5ee87d5cfdbe26

(Note there is another bug shown in the video, #226, where deleted environments are being pulled even after they are deleted)

### PR DESCRIPTION
**Pull request by half-ogre**
This PR fixes #225 and #226 by working around the current API behavior.

### CODE REVIEW

File: internal/database/database.go [hunk 1]
```diff
@@ -9,10 +9,18 @@ import (
 	"github.com/Hyphen/cli/pkg/errors"
 )
 
-type Database struct {
+type Database interface {
```
Comment (kylekampy) [inline internal/database/database.go]: ♥️

**Review by kylekampy — APPROVED** [review]
I think this looks great. Thanks for making these improvements, Drew.
